
jcf:
  datasource:
    A:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.12.36:3306/poss?useUnicode=true&amp;characterEncoding=UTF-8
      username: poss
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
  route:
    default-label: A
