jcf:
  datasource:
    A:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aaaa?useUnicode=true&amp;characterEncoding=UTF-8
      username: aaaa
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
  route:
    default-label: A
